/* Lexical Part */

id : 'a'-'z' {'a'-'z'} ;

!whitespace : ' ' | '\t' | '\n' | '\r' ;

/* Syntax Part */

<< import "github.com/go-serv/internal/compiler/ast" >>

World
    : Animals << ast.NewWorld($0) >> 
    ;

Animals
    : Animals Animal << ast.AppendAnimals($0, $1) >>
    | empty << ast.NewAnimalList() >>
    ;

Animal
    : id << ast.NewAnimal($0) >> 
    ;